FROM hub.furycloud.io/mercadolibre/nodejs:14-mini-runtime as builder
FROM gcr.io/distroless/nodejs:10
COPY --from=builder /app /app
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["/nodejs/bin/node", "index.js"]
