FROM node:current-buster-slim as build

# Now copy it into our base image.
FROM gcr.io/distroless/base-debian10:debug
COPY --from=build /usr/local/bin/node* /usr/bin/
COPY --from=build /usr/local/bin/npm /usr/bin/
COPY --from=build /usr/local/lib/ /usr/local/lib/
COPY --from=build /lib /lib
ENV LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
#CMD ["/app"]
